from src.components.Ecosystem import Ecosystem
from src.components.Dex import Dex

dex = Dex(20, 10000000)
print(dex.insrPrice)
print(dex.transactBuyInsr(0.00002))
print(dex.insrPrice)
print(dex.transactBuyInsr(1))
print(dex.insrPrice)
print(dex.transactBuyInsr(1))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactBuyInsr(0.00002))
print(dex.insrPrice)
print(dex.transactBuyInsr(1))
print(dex.insrPrice)
print(dex.transactBuyInsr(1))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
print(dex.transactSellInsr(250000))
print(dex.insrPrice)
